services:
  postgres:
    image: postgres:15-alpine
    container_name: underfrog-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/tables:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: underfrog-app
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  # dashboard:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.notebook
  #   container_name: underfrog-dashboard
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "0.0.0.0:8083:8080"
  #     # replace with a different port if needed
  #   volumes:
  #     - ./sql:/sql
  #     - ./.env:/sql/.env
  #   command: python /sql/dashboard_app.py
  
  

volumes:
  postgres_data:
