FROM python:3.14

WORKDIR /sql

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY sql/ .

EXPOSE 8888

ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=", "--NotebookApp.password="]
