services:
  postgres:
    image: postgres:15-alpine
    container_name: underfrog-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/tables:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: underfrog-app
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  notebooks:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    container_name: underfrog-notebooks
    depends_on:
      - postgres
    ports:
      - "0.0.0.0:8888:8888"
    volumes:
      - ./notebooks:/notebooks

volumes:
  postgres_data:
