services:
  postgres:
    image: postgres:15-alpine
    container_name: underfrog-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/tables:/docker-entrypoint-initdb.d # This change mounts the entire tables directory instead of a single SQL file

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: underfrog-app
    depends_on:
      - postgres
    ports:
      - "8081:8080"

volumes:
  postgres_data:
