spring:
  application:
    name: trade-executor
server:
  address: 0.0.0.0
  port: 8081

service:
  orders:
    url: ${ORDERS_URL:http://orders-service:8081/api/orders}
  instruments:
    url: ${INSTRUMENTS_URL:http://instruments-service:8081/api/instruments}
